name: Rust CI
on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_dispatch:

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - native/cozonomono_cozo/Cargo.toml

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            native/cozonomono_cozo

      - name: run rustfmt
        run: cargo fmt --manifest-path=${{ matrix.manifest }} --all -- --check

      - name: run clippy
        run: cargo clippy --manifest-path=${{ matrix.manifest }} -- -Dwarnings

